# Generated by Django 2.2.5 on 2020-02-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='contact_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
