# Generated by Django 2.2.5 on 2021-03-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Customer',
            new_name='customer',
        ),
    ]
